### ISSUE TITLE
Add remaining metrics to OpenRefine

### ISSUE THREAD

**Issue by nfriesen** [diachron/quality-extension#10]
All the metrics available here:
https://github.com/diachron/quality-extension/tree/master/src/com/google/refine/quality/metrics
should be integrated into OpenRefine

**Comment by clange** [comment]
I'm closing this for now; @ahsaniqbal I hope that's also fine with you. I assume that either the work has been done, or, if not, we can at some point reopen an issue specific to certain metrics that have not yet been integrated.
